// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// EvalConfetti
List EvalConfetti(NumericVector pars, int ngen, int nsteps_out, int ntrees, double xext, double yext, double rmax, double bw1);
RcppExport SEXP confettiRbasic_EvalConfetti(SEXP parsSEXP, SEXP ngenSEXP, SEXP nsteps_outSEXP, SEXP ntreesSEXP, SEXP xextSEXP, SEXP yextSEXP, SEXP rmaxSEXP, SEXP bw1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< int >::type ngen(ngenSEXP);
    Rcpp::traits::input_parameter< int >::type nsteps_out(nsteps_outSEXP);
    Rcpp::traits::input_parameter< int >::type ntrees(ntreesSEXP);
    Rcpp::traits::input_parameter< double >::type xext(xextSEXP);
    Rcpp::traits::input_parameter< double >::type yext(yextSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< double >::type bw1(bw1SEXP);
    __result = Rcpp::wrap(EvalConfetti(pars, ngen, nsteps_out, ntrees, xext, yext, rmax, bw1));
    return __result;
END_RCPP
}
